default_agent: langgraph_agent
agents:
  langgraph_agent:
    name: langgraph_agent
    entrypoint: agent_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::313117444016:role/LangGraphAgentCoreRole
      execution_role_auto_create: false
      account: '313117444016'
      region: us-west-2
      ecr_repository: 313117444016.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-langgraph_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: langgraph_agent-1NyH76Cfc7
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:313117444016:runtime/langgraph_agent-1NyH76Cfc7
      agent_session_id: dae9d2a0-9c80-454b-adc0-6f3179dace73
    codebuild:
      project_name: bedrock-agentcore-langgraph_agent-builder
      execution_role: arn:aws:iam::313117444016:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-cc650878d6
      source_bucket: bedrock-agentcore-codebuild-sources-313117444016-us-west-2
    memory:
      mode: STM_ONLY
      memory_id: langgraph_agent_mem-o5nDQxAbkB
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:313117444016:memory/langgraph_agent_mem-o5nDQxAbkB
      memory_name: langgraph_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
